config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  # Defines the root path route ("/")
  root 'importations#new'
  resources :importations, only: [:new, :create] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :cards 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  validates :firstname,:lastname,:partner, presence: true
  validates :link, presence: true, format: { with: /\Ahttps?:\/\/\S+\z/ }

end

app/models/importation.rb
class Importation < ApplicationRecord
  has_one_attached :file
  validates :file, presence: true

  def file_url
    self.file.attached? ? Rails.application.routes.url_helpers.rails_blob_path(self.file, only_path: true) : ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards
  def index

    @pagy, @cards = pagy(Card.all, items: 10)
  end

  # PDF generator 
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "badge #{@card.fullname}",
              orientation: "Portrait",
              page_size: 'A4',
              layout: 'pdf',
              formats: [:pdf],
              encoding: 'UTF-8',
              locale: 'fr'
      end
    end
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy!

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:firstname, :lastname, :link, :partner)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/importations_controller.rb
class ImportationsController < ApplicationController
  def new
    @importation = Importation.new
  end
  
  def create
    @importation = Importation.new(importation_params)
    
    if @importation.save
      ImportationExcelWorker.perform_async(@importation.id)
      flash[:success] = "L'importation des données Excel est programmée !"
      sleep(3) # Ajouter un délai de 3 secondes
      redirect_to cards_path
    else
      flash[:error] = "Veuillez sélectionner un fichier à importer."
      render :new
    end
  end

  def destroy_all
    Importation.destroy_all
    Card.destroy_all
    flash[:success] = "Toutes les données d'importation ont été supprimées avec succès."
    redirect_to root_path
  end

  private

  def importation_params
    params.require(:importation).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  ALERT_CSS = {
    'alert' => 'bg-red-100 text-red-700',
    'error' => 'bg-red-100 text-red-700',
    'success' => 'bg-green-100 text-green-700',
    'notice' => 'bg-blue-100 text-blue-700'
  }

  def alert_style(value)
    ALERT_CSS[value]
  end

   def qr_code_as_svg(uri)
    RQRCode::QRCode.new(uri).as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 3,
      standalone: true
    ).html_safe
  end

  def extract_from_url(link)
    File.basename(link)
  end

  def extract_numbers_from_url(link)
  match = link.match(/https:\/\/i-pay.money\/subscriber_payment_desks\/(\d+)/)
  if match
    numbers = match.captures[0]
    return numbers.to_i
  else
    return nil
  end
end


end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/importations_helper.rb
module ImportationsHelper
end

app/views/cards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card</h1>

  <%= render "form", card: @card %>

  <%= link_to "Show this card", @card, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/index.html.erb
<div class="w-full px-40 p3-5 relative">
  <div class="overflow-x-auto">
    <h1 class="font-bold text-4xl my-5">Listes importés</h1>
    <turbo-frame id="cards">
      <table class="min-w-full border divide-y">
        <thead class='bg-indigo-600 text-white'>
          <tr>
            <th class='p-1'>#</th>
            <th class="p-1 text-left border">Code</th>
            <th class="p-1 text-left border">Nom</th>
            <th class="p-1 text-left border">Liens</th>
            <th class="p-1 text-center border">#</th>
          </tr>
        </thead>
        <tbody>
          <% @cards.each_with_index do |card, index| %>
            <tr>
              <td class='p-1 text-center border bg-gray-100'><%= index + 1 %></td>
              <td class="p-1 whitespace-nowrap border"><%= card.code %></td>
              <td class="p-1 whitespace-nowrap border"><%= card.fullname %></td>
              <td class="p-1 whitespace-nowrap border text-indigo-700"><%= card.link %></td>
              <td class="p-1 border flex items-center justify-center">
                <div class='flex gap-2 items-center'>
                  <%= link_to  card_path(card, format: :pdf), target: "_blank" do %>
                    <%= image_tag "print.gif", width: 40 %>
                  <% end %>
                  <%= button_to 'x', card_path(card), method: :delete, class: "text-sm bg-red-500 text-red-100 py-1 px-2 rounded shadow" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </turbo-frame>
    <div class="mt-2 float-right">
      <%== pagy_nav(@pagy) %> 
    </div>
  </div>
  <div class='fixed bottom-10 right-10 rounded-full border border-pink-500 p-3 shadow-lg'>
    <%= link_to root_path do %>
    <%= image_tag "home.gif", width: 60 %>
    <% end %>
  </div>
</div>

app/views/cards/show.pdf.erb
<section style="padding: 15px 0; display: flex; justify-content: space-between; font-family: Calibri, sans-serif;">
  <div style="flex: grow; width: 45%; padding: 0 15px; display: inline-block; position: relative">
    <section style='display: flex; justify-content: space-between; align-items: center'>
      <span style='font-size: 20px'>GUIDE PAIEMENT PRIME ASSURANCE</span>
      <span style='font-size: 18px; font-weight: bold; margin: 10px 0 -5px'><%= image_tag wicked_pdf_asset_base64("ipay.png"), width: 42 %></span>
    </section>

    <section style='text-align: center'>
      <span style='font-size: 18px; font-weight: 600; text-transform: uppercase;'><%= @card.fullname %></span>
    </section>
    <br>
    <section style='text-align: center; margin: -22px 0'>
      <%= image_tag wicked_pdf_asset_base64("logo.png"), width: 180 %>
    </section>
    <br>
    <section style='text-align: center; margin: 12px 0'>
      <span style='font-size: 17px;'>CODE DE PAIEMENT en agence Alizza ou BOA</span>
      <br>
      <span style='font-size: 23px; font-weight: bold'>
        <%# <%= @card.code %> 
        <%= extract_numbers_from_url(@card.link) %>
      </span>
    </section>
    
    <section style='text-align: center'>
      <div>Ou</div>
      <div style='font-size: 20px;'>Scannez pour payer avec téléphone</div>
    </section>
    <br>
    <section style='text-align: center'>
      <%= qr_code_as_svg(@card.link) %>
    </section>

    <section style='text-align: center; margin-top: 12px'>
      <div style='font-size: 17px; font-weight: 300; color: #07049b'><%= @card.link %></div>
      <div style='font-size: 15px; font-weight: 800; margin: 10px 0'>PAYEZ PAR :</div>
    </section>

    <section style='text-align: center'>
      <%= image_tag wicked_pdf_asset_base64("part.png"), width: 380 %>
    </section>

    <section style='text-align: center; margin-top: 10px'>
      <div style='font-size: 20px; font-weight: 800'>Service Client</div>
      <div style='font-size: 15px; margin: 10px 0'>(+227) 87 50 50 50 /  (+227) 20 73 41 75</div>
    </section>
    
  </div>
  
  <div style="width: 44%; padding: 0 15px; display: inline-block;">
    <section style='display: flex; justify-content: space-between; align-items: center'>
        <span style='font-size: 24px; font-weight: bold; margin-top: 10px'>GUIDE PAIEMENT PRIME ASSURANCE</span>
        <span><%= image_tag wicked_pdf_asset_base64("ipay.png"), width: 42 %></span>
    </section>
    
    <section style='margin: 17px 0'>
      <h3>Mode 1:</h3>
      <p style='text-align: justify; font-size: 17px'>Utilisez le code de paiement et dirigez-vous vers l'une des agences Alizza ou BOA Niger pour procéder au règlement de votre prime d'assurance</p>
    </section>

    <section style='margin: 17px 0'>
      <h3>Mode 2:</h3>
      <p style='text-align: justify; font-size: 17px'>Scannez le code QR avec l’appareil photo de votre téléphone et effectuez le paiement de votre prime d'assurance en utilisant VISA & MasterCard, MyBOA et le Mobile Money (Airtel Money et Moov Money).
      </p>
    </section>
    
    <section style='margin: 17px 0'>
      <h3>Mode 3:</h3>
      <p style='text-align: justify; font-size: 17px'>Effectuez le règlement de votre prime d'assurance en utilisant votre carte bancaire, que ce soit une carte VISA ou MasterCard.
    </p>
    </section>
    
    <section style='text-align: center; margin-top: 30px'>
      <h3 style='margin-bottom: -5px'>Service Client</h3>
      <p>(+227) 87 50 50 50 /  (+227) 20 73 41 75</p>
    </section>
  </div>
</section>

app/views/importations/new.html.erb
<div class="flex flex-wrap min-h-screen w-full content-center justify-center bg-gray-200 py-10">
  
  <!-- Login component -->
  <div class="flex shadow-md">
    <!-- Login form -->
    <div class="flex flex-wrap content-center justify-center rounded-l-md bg-white relative" style="width: 26rem; height: 32rem;">
      <div class="w-[21rem]">
        <!-- Heading -->
        <h1 class="text-2xl font-semibold mb-5 text-cyan-700 uppercase">Badge Generator</h1>

        <!-- Form -->
        <%= form_with(model: @importation, url: importations_path, local: true, html: { multipart: true }) do |form| %>
          <div class="mb-6">
            <%= form.label :file, 'Sélectionnez un fichier Excel', class: "block text-gray-700 text-sm font-bold mb-2 hidden" %>
            <%= form.file_field :file, accept: '.xlsx', class: "border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline w-min" %>
          </div>

          <div class="mb-6">
            <%= form.submit 'Importer', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
          </div>
        <% end %>

        <div>
          <%= button_to "Purger", destroy_all_importations_path, method: :delete, data: { confirm: "Êtes-vous sûr ? Cette action supprimera toutes les données d'importation." }, class: "fixed bottom-40 bg-pink-700 py-2 px-3 text-pink-50 rounded shadow" %>
        </div>
      </div>
    </div>

    <!-- Login banner -->
    <div class="flex flex-wrap content-center justify-center rounded-r-md" style="width: 26rem; height: 32rem;">
      <%= link_to cards_path, class:'h-full' do %>
        <%= image_tag "fond.jpg", class: "w-full h-full bg-center bg-no-repeat bg-cover rounded-r-md" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Badge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render "shared/notification" %> 
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Badge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_notification.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <div class="max-w-[600px] py-4 px-5 font-bold <%= alert_style(key)  %> animated fixed z-50 flex rounded-lg p-4 mb-4 text-sm shadow-xl <%= alert_style(key) %>" role="alert" data-controller="notification"
      data-notification-delay-value="5000">
      <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <div>
        <span class="font-medium"><%= value %></span>
      </div>
    </div>
  <% end %>
<% end %>